language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      cmake
      python-pip

install:
  - pip install --user -r requirements.txt

script:
  - make -j test
  - travis_wait 600 make -j run
