# Azure DevOps CI Configuration

# Use standard Ubuntu 16.04 host
pool:
  name: Hosted Ubuntu 1604

# Execution Steps
steps:
# Use Python 3.6
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6
# Update pip and install gcovr
- script: |
   python -m pip install --upgrade pip 
   pip install gcovr
  displayName: 'Install Dependencies'
# Build main binary
- script: 'make -j'
  displayName: 'Make Main'
# Build tests
- script: 'make -j test'
  displayName: 'Make Tests'
# Publish test report
- task: PublishTestResults@1
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/cppdatastructs/test/unittests/cppdatastructstest_unittests.xml'
# Publish test coverage
- task: PublishCodeCoverageResults@2
  displayName: 'Publish Test Coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: build/cppdatastructs/test/unittests/cppdatastructstest_coverage.xml
