# Azure DevOps CI Configuration

pool:
  name: Hosted Ubuntu 1604

steps:
- task: UsePythonVersion@0
  displayName: 'Set Environment to use Python 3.6'
  inputs:
    versionSpec: 3.6
- script: 'sudo apt install lcov'
  displayName: 'Install Ubuntu Packages'
- script: |
   python -m pip install --upgrade pip 
   pip install -r requirements.txt
  displayName: 'Install Python Dependencies'
- script: 'make -j test'
  displayName: 'Build and Run Tests'
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build/cppdatastructs/test/unittests/cppdatastructstest_unittests.xml'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Test Coverage'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: build/cppdatastructs/test/unittests/cppdatastructstest.xml
- script: 'make -j run'
  displayName: 'Build and Run Main'
  timeoutInMinutes: 360
